import turtle;
screen = turtle.Screen()
road_pen = turtle.Turtle()
road_pen.penup()
road_pen.goto(-100, -100)
road_pen.pendown()
road_pen.fd(100)
road_pen.lt(90)
road_pen.fd(200)
road_pen.lt(90)
road_pen.fd(100)
road_pen.lt(90)
road_pen.fd(200)
screen.exitonclick()